# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_time', 'title'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='article',
            name='visiter',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
